name: Exercice pipelines
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get codes
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '20.18'
            - name: Install dependencies
              run: npm ci
            - name: Lint with ESLint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Get codes
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '20.18'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Get codes
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '20.18'
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: deploy
              run: echo "deploy app..."
